# Generated by Django 4.2.7 on 2023-11-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_complete_name_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='complete_name',
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Nome do meio'),
        ),
    ]
