# Generated by Django 4.2.7 on 2023-11-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_complete_name_user_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
    ]
