# Generated by Django 4.2.7 on 2023-11-26 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Código')),
                ('level', models.CharField(choices=[('M', 'Maternal'), ('J1', 'Jardim 1'), ('J2', 'Jardim 2'), ('1', '1ª Ano'), ('2', '2ª Ano'), ('3', '3ª Ano'), ('4', '4ª Ano'), ('5', '5ª Ano'), ('6', '6ª Ano'), ('7', '7ª Ano'), ('8', '8ª Ano'), ('9', '9ª Ano'), ('1M', '1º Ano - Médio'), ('2M', '2º Ano - Médio'), ('3M', '3º Ano - Médio')], max_length=50, verbose_name='Nível')),
                ('academic_year', models.IntegerField(verbose_name='Ano Letivo')),
                ('enrolled', models.ManyToManyField(blank=True, related_name='matriculados', to=settings.AUTH_USER_MODEL, verbose_name='Matriculados')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('syllabus', models.TextField(blank=True, null=True, verbose_name='Ementa')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=200, unique=True)),
                ('academic_probation', models.ManyToManyField(blank=True, related_name='academic_probation', to=settings.AUTH_USER_MODEL, verbose_name='Dependência')),
                ('class_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.class', verbose_name='Turma')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Professor')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_test', models.CharField(choices=[('1', '1ª Avaliação'), ('2', '2ª Avaliação'), ('3', '3ª Avaliação'), ('4', '4ª Avaliação'), ('PF', 'Prova Final')], max_length=50, verbose_name='Prova')),
                ('date', models.DateField(verbose_name='Data')),
                ('class_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.class', verbose_name='Turma')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject', verbose_name='Disciplina')),
            ],
            options={
                'verbose_name': 'Prova',
                'verbose_name_plural': 'Provas',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(verbose_name='Nota')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Aluno')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.test', verbose_name='Prova')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='main/events', verbose_name='Imagem')),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('date_time', models.DateTimeField(verbose_name='Data e Hora')),
                ('enrolled', models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL, verbose_name='Participantes')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('class_diary', models.TextField(verbose_name='Diário de Classe')),
                ('attendance_list', models.ManyToManyField(related_name='students_present', to=settings.AUTH_USER_MODEL, verbose_name='lista de presença')),
                ('class_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.class', verbose_name='Turma')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject', verbose_name='Disciplina')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('prompt', models.TextField(verbose_name='Enunciado')),
                ('image', models.ImageField(blank=True, null=True, upload_to='main/activities', verbose_name='Imagem')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('delivery_date', models.DateField(verbose_name='Data de entrega')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject', verbose_name='Disciplina')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
            },
        ),
    ]
