# Generated by Django 4.2.7 on 2023-11-06 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('prompt', models.TextField(verbose_name='Enunciado')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('delivery_date', models.DateField(verbose_name='Data de entrega')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Código')),
                ('level', models.CharField(max_length=50, verbose_name='Nível')),
                ('academic_year', models.IntegerField(verbose_name='Ano Letivo')),
                ('enrolled', models.ManyToManyField(related_name='matriculados', to=settings.AUTH_USER_MODEL, verbose_name='Matriculados')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('class_diary', models.TextField(verbose_name='Diário de Classe')),
                ('attendance_list', models.ManyToManyField(related_name='students_present', to=settings.AUTH_USER_MODEL, verbose_name='lista de presença')),
                ('class_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.class', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('date_time', models.DateTimeField(verbose_name='Data e Hora')),
                ('enrolled', models.ManyToManyField(related_name='participants', to=settings.AUTH_USER_MODEL, verbose_name='Participantes')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(verbose_name='Nota')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('syllabus', models.TextField(verbose_name='Ementa')),
                ('academic_probation', models.ManyToManyField(related_name='academic_probation', to=settings.AUTH_USER_MODEL, verbose_name='Dependência')),
                ('class_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.class', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_test', models.CharField(choices=[('1', '1ª Avaliação'), ('1R', 'Recuperação 1'), ('2', '2ª Avaliação'), ('2R', 'Recuperação 2'), ('3', '3ª Avaliação'), ('3R', 'Recuperação 3'), ('4', '4ª Avaliação'), ('4R', 'Recuperação 4'), ('PF', 'Prova Final')], max_length=50, verbose_name='Prova')),
                ('date', models.DateField(verbose_name='Data')),
                ('class_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.class', verbose_name='Turma')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject', verbose_name='Disciplina')),
            ],
            options={
                'verbose_name': 'Prova',
                'verbose_name_plural': 'Provas',
            },
        ),
        migrations.DeleteModel(
            name='Disciplina',
        ),
        migrations.AddField(
            model_name='grade',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.test', verbose_name='Prova'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject', verbose_name='Disciplina'),
        ),
        migrations.AddField(
            model_name='activity',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject', verbose_name='Disciplina'),
        ),
    ]
