# Generated by Django 4.2.7 on 2023-11-06 13:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_activity_class_classroom_event_grade_subject_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='main/activities', verbose_name='Imagem'),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='main/events', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='class',
            name='enrolled',
            field=models.ManyToManyField(blank=True, null=True, related_name='matriculados', to=settings.AUTH_USER_MODEL, verbose_name='Matriculados'),
        ),
        migrations.AlterField(
            model_name='class',
            name='level',
            field=models.CharField(choices=[('M', 'Maternal'), ('J1', 'Jardim 1'), ('J2', 'Jardim 2'), ('1', '1ª Ano'), ('2', '2ª Ano'), ('3', '3ª Ano'), ('4', '4ª Ano'), ('5', '5ª Ano'), ('6', '6ª Ano'), ('7', '7ª Ano'), ('8', '8ª Ano'), ('9', '9ª Ano'), ('1M', '1º Ano - Médio'), ('2M', '2º Ano - Médio'), ('3M', '3º Ano - Médio')], max_length=50, verbose_name='Nível'),
        ),
        migrations.AlterField(
            model_name='event',
            name='enrolled',
            field=models.ManyToManyField(blank=True, null=True, related_name='participants', to=settings.AUTH_USER_MODEL, verbose_name='Participantes'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='academic_probation',
            field=models.ManyToManyField(blank=True, null=True, related_name='academic_probation', to=settings.AUTH_USER_MODEL, verbose_name='Dependência'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='syllabus',
            field=models.TextField(blank=True, null=True, verbose_name='Ementa'),
        ),
    ]
