# Generated by Django 4.2.7 on 2023-11-18 14:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_activity_image_event_image_alter_class_enrolled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='enrolled',
            field=models.ManyToManyField(blank=True, related_name='matriculados', to=settings.AUTH_USER_MODEL, verbose_name='Matriculados'),
        ),
        migrations.AlterField(
            model_name='event',
            name='enrolled',
            field=models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL, verbose_name='Participantes'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='academic_probation',
            field=models.ManyToManyField(blank=True, related_name='academic_probation', to=settings.AUTH_USER_MODEL, verbose_name='Dependência'),
        ),
    ]
